# Generated by Django 3.1.7 on 2021-09-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('JD', '京东'), ('TEST', '测试数据'), ('OTHER', '其他')], default='JD', max_length=5, verbose_name='数据来源')),
                ('content', models.CharField(max_length=1000, verbose_name='内容')),
                ('arthur', models.CharField(max_length=64, verbose_name='作者')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('link', models.CharField(max_length=64, verbose_name='链接')),
            ],
        ),
    ]
